const assert = require('node:assert/strict');
const { createFinanceSnapshot, calculateTechnicianPay, ensureFinanceSnapshots, buildReport, exportFinanceXml } = require('../backend/src/domain/finance');
const { validateBusinessConfig, EMPTY_BUSINESS_CONFIG } = require('../backend/src/domain/business-config');
const { DEFAULT_BUSINESS_CONFIG } = require('../mock-api/businessConfig');
const policy = { revenueRecognition: 'completed', technicianPayType: 'percentage', technicianPayRate: 40, includePartsInCommission: false };
const job = { id: 'P0', status: 'completed', finalPrice: 1000000, partsCost: 400000, paymentStatus: 'unpaid', completedAt: '2026-09-01T03:00:00.000Z', customerName: '<script>&test', applianceType: 'Điều hòa' };
assert.equal(calculateTechnicianPay(job, policy), 240000);
assert.equal(calculateTechnicianPay(job, { ...policy, includePartsInCommission: true }), 400000);
assert.equal(calculateTechnicianPay(job, { ...policy, technicianPayRate: 0 }), 0);
assert.equal(calculateTechnicianPay(job, { ...policy, technicianPayType: 'fixed', technicianPayRate: 123000 }), 123000);
assert.equal(calculateTechnicianPay({ ...job, partsCost: 2000000 }, policy), 0);
assert.equal(calculateTechnicianPay({ ...job, finalPrice: 100001, partsCost: 0 }, policy), 40000);
const snapshot = createFinanceSnapshot(job, policy);
assert.equal(calculateTechnicianPay({ ...job, financeSnapshot: snapshot }, { ...policy, technicianPayRate: 80 }), 240000);
const corrected = createFinanceSnapshot({ ...job, partsCost: 500000 }, snapshot.policy, undefined, 'finance-correction');
assert.equal(corrected.technicianPay, 200000);
assert.equal(snapshot.technicianPay, 240000);
const db = { settings: { businessConfig: { finance: policy } }, technicians: [], serviceRequests: [structuredClone(job)] };
assert.equal(ensureFinanceSnapshots(db), true);
assert.equal(ensureFinanceSnapshots(db), false);
db.settings.businessConfig.finance = { ...policy, technicianPayRate: 80 };
assert.equal(buildReport(db, '2026-09').totals.technicianPay, 240000);
db.settings.businessConfig.finance.revenueRecognition = 'paid';
assert.equal(buildReport(db, '2026-09').totals.revenue, 0);
db.serviceRequests[0].paymentStatus = 'paid'; db.serviceRequests[0].paidAt = '2026-10-01T03:00:00Z';
assert.equal(buildReport(db, '2026-09').totals.revenue, 0);
assert.equal(buildReport(db, '2026-10').totals.revenue, 1000000);
assert.ok(exportFinanceXml(buildReport(db, '2026-10'), '2026-10').includes('&lt;script&gt;&amp;test'));
validateBusinessConfig(structuredClone(EMPTY_BUSINESS_CONFIG));
validateBusinessConfig(structuredClone(DEFAULT_BUSINESS_CONFIG));
for (const invalid of [null, [], {}, { ...DEFAULT_BUSINESS_CONFIG, finance: { ...policy, technicianPayRate: -1 } }, { ...DEFAULT_BUSINESS_CONFIG, finance: { ...policy, technicianPayRate: 101 } }, { ...DEFAULT_BUSINESS_CONFIG, appliances: {} }, { ...DEFAULT_BUSINESS_CONFIG, appliances: [null] }, { ...DEFAULT_BUSINESS_CONFIG, pricing: { ...DEFAULT_BUSINESS_CONFIG.pricing, inspectionFee: NaN } }, { ...DEFAULT_BUSINESS_CONFIG, appliances: [DEFAULT_BUSINESS_CONFIG.appliances[0], DEFAULT_BUSINESS_CONFIG.appliances[0]] }]) assert.throws(() => validateBusinessConfig(invalid));
console.log('P0 domain: pay parity, zero/fixed/rate changes, snapshots, recognition and config validation PASS');

const { businessDate } = require('../backend/src/domain/finance');
assert.equal(businessDate('2026-08-31T18:00:00Z'), '2026-09-01');
assert.equal(businessDate('2026-09-30T18:00:00Z'), '2026-10-01');
assert.equal(businessDate(null), '');
