const assert = require('assert'); const fs = require('fs'); const { spawn } = require('child_process');
const dbPath='mock-api/mock-db.json', original=fs.readFileSync(dbPath,'utf8');
const server=spawn(process.execPath,['mock-api/server.js'],{env:{...process.env,PORT:'3014',SERVICE_ONLY:'true',NODE_ENV:'development',ENABLE_DEV_ENDPOINTS:'true',LOOKUP_TEST_OTP:'123456'},stdio:['ignore','pipe','pipe']});
const base='http://127.0.0.1:3014/api/v1'; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function call(path, options={}) { const r=await fetch(base+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}); let data={}; try{data=await r.json();}catch{} return {status:r.status,data,headers:r.headers}; }
const cookie = response => response.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
const booking = {customerName:'A',customerPhone:'0901234567',customerAddress:'1 Test',district:'Quận Cầu Giấy',
    areaId: 'cau-giay',serviceCategoryId:'ve-sinh-dieu-hoa',applianceType:'Điều hòa',issueDescription:'Can kiem tra may',preferredDate:new Date(Date.now()+86400000).toISOString().slice(0,10),preferredTimeSlot:'08:00 - 10:00',images:[],mediaMetadata:[]};
(async()=>{ try { await sleep(500); const loginA=await call('/auth/login',{method:'POST',body:JSON.stringify({email:'a@test.vn',phone:'0901234567'})}); const cookieA=cookie(loginA); const created=await call('/service-requests',{method:'POST',headers:{Cookie:cookieA},body:JSON.stringify(booking)}); assert.equal(created.status,201); const id=created.data.data.id; const own=await call(`/me/service-requests/${id}`,{headers:{Cookie:cookieA}}); assert.equal(own.status,200); const loginB=await call('/auth/login',{method:'POST',body:JSON.stringify({email:'b@test.vn',phone:'0901234567'})}); const other=await call(`/me/service-requests/${id}`,{headers:{Cookie:cookie(loginB)}}); assert.equal(other.status,404,'same phone must not grant ownership'); const guest=await call('/service-requests',{method:'POST',body:JSON.stringify({...booking,customerPhone:'0909999999'})}); const db=JSON.parse(fs.readFileSync(dbPath)); assert.equal(db.serviceRequests.find(x=>x.id===id).userId,loginA.data.data.id); assert.equal(db.serviceRequests.find(x=>x.id===guest.data.data.id).userId,null);
const unknown=await call('/service-requests/lookup/request-otp',{method:'POST',body:JSON.stringify({requestCode:'SR-NOTREAL',phone:'0900000000'})}); const requested=await call('/service-requests/lookup/request-otp',{method:'POST',body:JSON.stringify({requestCode:id,phone:'0901234567'})}); assert.equal(unknown.status,requested.status); assert.equal(unknown.data.message,requested.data.message,'enumeration responses differ'); const otp='123456'; for(let attempt=0;attempt<5;attempt++) assert.equal((await call('/service-requests/lookup/verify',{method:'POST',body:JSON.stringify({requestCode:id,otp:'000000'})})).status,401); assert.equal((await call('/service-requests/lookup/verify',{method:'POST',body:JSON.stringify({requestCode:id,otp})})).status,401,'locked grant accepted correct OTP'); await call('/service-requests/lookup/request-otp',{method:'POST',body:JSON.stringify({requestCode:id,phone:'0901234567'})}); const verified=await call('/service-requests/lookup/verify',{method:'POST',body:JSON.stringify({requestCode:id,otp})}); const token=verified.data.data.token; const detail=await call(`/service-requests/lookup/${id}`,{headers:{Authorization:`Lookup ${token}`}}); assert.equal(detail.status,200); for(const secret of ['customerPhone','customerAddress','images','statusHistory','internalSecret']) assert(!(secret in detail.data.data),`guest leaked ${secret}`); const wrongScope=await call(`/service-requests/lookup/${guest.data.data.id}`,{headers:{Authorization:`Lookup ${token}`}}); assert.equal(wrongScope.status,401); const legacy=await call(`/service-requests/${id}?phone=0901234567`); assert.equal(legacy.status,404); console.log('PASS: account ownership, guest OTP scope, enumeration safety and explicit guest DTO'); } finally {server.kill('SIGTERM');fs.writeFileSync(dbPath,original);} })().catch(e=>{console.error(e);process.exitCode=1});
