const assert=require('assert'),fs=require('fs'),{spawn}=require('child_process');
const path='mock-api/mock-db.json', original=fs.readFileSync(path,'utf8'), db=JSON.parse(original); const baseRequest=db.serviceRequests[0], baseTech=db.technicians[0];
db.serviceRequests=Array.from({length:35},(_,i)=>({...baseRequest,id:`SR-PAGE-${String(i+1).padStart(2,'0')}`,customerName:`Pagination Customer ${String(i+1).padStart(2,'0')}`,customerPhone:`091111${String(i+1).padStart(4,'0')}`,createdAt:`2026-09-${String((i%20)+1).padStart(2,'0')}T12:00:00.000Z`,preferredDate:`2026-10-${String((i%20)+1).padStart(2,'0')}`}));
db.serviceRequests[0].id='SR-VN-BEFORE';db.serviceRequests[0].createdAt='2026-09-13T16:30:00.000Z';db.serviceRequests[0].preferredDate='2026-10-20';
db.serviceRequests[1].id='SR-VN-AFTER';db.serviceRequests[1].createdAt='2026-09-13T17:30:00.000Z';db.serviceRequests[1].preferredDate='2026-11-20';
db.technicians=Array.from({length:15},(_,i)=>({...baseTech,id:`TECH-PAGE-${String(i+1).padStart(2,'0')}`,name:`Technician Pagination ${String(i+1).padStart(2,'0')}`,phone:`090000${String(i+1).padStart(4,'0')}`,email:`tech${i+1}@page.test`})); fs.writeFileSync(path,JSON.stringify(db,null,2)+'\n');
const server=spawn(process.execPath,['mock-api/server.js'],{env:{...process.env,PORT:'3015',SERVICE_ONLY:'true',ENABLE_DEMO_ACCOUNTS:'true',DEMO_ADMIN_EMAIL:'owner@test.local',DEMO_ADMIN_PASSWORD:'OwnerPass123!'},stdio:['ignore','pipe','pipe']}); const base='http://127.0.0.1:3015/api/v1';
async function call(url,opt={}){const r=await fetch(base+url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});return {status:r.status,body:await r.json()};}
(async()=>{try{await new Promise(r=>setTimeout(r,500));const login=await call('/admin/auth/login',{method:'POST',body:JSON.stringify({email:'owner@test.local',password:'OwnerPass123!'})});const token=login.body.data.token,h={Authorization:`Bearer ${token}`};
let r=await call('/admin/service-requests?page=4&limit=10&sortBy=createdAt&sortOrder=asc',{headers:h});assert.deepEqual(r.body.meta,{page:4,limit:10,total:35,totalPages:4});assert.equal(r.body.data.length,5);
r=await call('/admin/service-requests?page=1&limit=10&q=Pagination%20Customer%2035',{headers:h});assert.equal(r.body.meta.total,1);assert.equal(r.body.data[0].customerName,'Pagination Customer 35');
r=await call('/admin/technicians?page=2&limit=10&q=Technician%20Pagination',{headers:h});assert.deepEqual(r.body.meta,{page:2,limit:10,total:15,totalPages:2});assert.equal(r.body.data.length,5);
r=await call('/admin/service-requests?createdFrom=2026-09-14&createdTo=2026-09-14&limit=100',{headers:h});assert(!r.body.data.some(x=>x.id==='SR-VN-BEFORE'));assert(r.body.data.some(x=>x.id==='SR-VN-AFTER'));
r=await call('/admin/service-requests?scheduledFrom=2026-11-20&scheduledTo=2026-11-20',{headers:h});assert.equal(r.body.meta.total,1);assert.equal(r.body.data[0].id,'SR-VN-AFTER');
r=await call('/admin/customers?page=2&limit=10&q=Pagination',{headers:h});assert.equal(r.body.meta.totalPages,4);assert.equal(r.body.data.length,10);console.log('PASS: list meta, last pages, server search and separate Vietnam-time date filters');}finally{server.kill('SIGTERM');fs.writeFileSync(path,original);}})().catch(e=>{console.error(e);process.exitCode=1});
