import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ArrowRight, CalendarCheck, CheckCircle2, Clock3, MapPin, Radio, TrendingUp, UserCheck, UserRound, Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import LoadingState from '../components/ui/LoadingState';
import ErrorState from '../components/ui/EmptyState';
import ServiceRequestStatusBadge from '../features/service-requests/components/ServiceRequestStatusBadge';
import ServiceRequestSlaBadge from '../features/service-requests/components/ServiceRequestSlaBadge';
import type { ServiceRequest } from '../features/service-requests/types';
import type { Technician } from '../features/technicians/types';

const dateKey = (timestamp: number) => { const d = new Date(timestamp); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };

export default function Dashboard() {
  const requestsQuery = useQuery({ queryKey: ['admin-service-requests'], queryFn: async () => (await api.get('/admin/service-requests')).data, refetchInterval: 30000 });
  const techniciansQuery = useQuery({ queryKey: ['admin-technicians'], queryFn: async () => (await api.get('/admin/technicians')).data, refetchInterval: 30000 });
  if (requestsQuery.isLoading || techniciansQuery.isLoading) return <LoadingState message="Đang đồng bộ bảng điều phối..." />;
  if (requestsQuery.error || !requestsQuery.data?.success) return <ErrorState message="Không thể tải bảng điều phối" subMessage="Vui lòng kiểm tra kết nối API và thử lại." />;

  const requests: ServiceRequest[] = requestsQuery.data.data || [];
  const technicians: Technician[] = techniciansQuery.data?.data || [];
  const nowMs = requestsQuery.dataUpdatedAt;
  const today = dateKey(nowMs);
  const tomorrow = dateKey(nowMs + 86400000);
  const active = requests.filter(item => !['completed', 'cancelled'].includes(item.status));
  const overdue = active.filter(item => item.status === 'pending' && nowMs - new Date(item.createdAt).getTime() > 30 * 60000);
  const unassigned = active.filter(item => item.status === 'confirmed' && !item.assignedTechnicianId);
  const inProgress = active.filter(item => ['assigned', 'in_progress'].includes(item.status));
  const completedToday = requests.filter(item => item.status === 'completed' && item.updatedAt.startsWith(today));
  const revenueToday = completedToday.reduce((sum, item) => sum + Number(item.finalPrice || 0), 0);
  const queue = [...active].sort((a, b) => urgencyScore(b, nowMs) - urgencyScore(a, nowMs)).slice(0, 8);
  const availableTechs = technicians.filter(item => item.status === 'available').length;
  const confirmationRate = requests.length ? Math.round(requests.filter(item => item.status !== 'pending').length / requests.length * 100) : 0;

  return <div className="space-y-7 pb-10 page-fade-in">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-blue-600"><Radio className="h-4 w-4 animate-pulse" />Đang đồng bộ mỗi 30 giây</div><h1 className="text-3xl font-bold tracking-tight text-slate-950">Trung tâm điều phối</h1><p className="mt-2 text-sm text-slate-500">{new Date(nowMs).toLocaleDateString('vi-VN', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' })} · Ưu tiên những việc cần xử lý ngay.</p></div><Link to="/service-requests" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-bold text-white shadow-lg shadow-slate-900/10 transition hover:-translate-y-0.5 hover:bg-blue-700">Mở toàn bộ yêu cầu <ArrowRight className="h-4 w-4" /></Link></div>

    {overdue.length > 0 && <Link to="/service-requests" className="group flex items-center justify-between gap-4 overflow-hidden rounded-2xl border border-red-200 bg-gradient-to-r from-red-50 via-orange-50 to-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-red-600 text-white shadow-md shadow-red-600/20"><AlertTriangle className="h-6 w-6" /></span><div><p className="font-bold text-red-950">{overdue.length} khách đang chờ quá 30 phút</p><p className="mt-1 text-sm text-red-700">Liên hệ xác nhận ngay để bảo đảm SLA và tránh mất khách.</p></div></div><ArrowRight className="hidden h-5 w-5 text-red-600 transition-transform group-hover:translate-x-1 sm:block" /></Link>}

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={Clock3} tone="amber" label="Chờ xác nhận" value={requests.filter(item => item.status === 'pending').length} detail={`${overdue.length} quá SLA`} /><Kpi icon={UserRound} tone="blue" label="Chưa phân công" value={unassigned.length} detail={`${availableTechs} thợ đang sẵn sàng`} /><Kpi icon={Wrench} tone="cyan" label="Đang thực hiện" value={inProgress.length} detail={`${requests.filter(item => item.customerApprovalStatus === 'pending').length} chờ khách duyệt giá`} /><Kpi icon={CheckCircle2} tone="emerald" label="Hoàn thành hôm nay" value={completedToday.length} detail={new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(revenueToday)} /></div>

    <div className="grid gap-6 xl:grid-cols-[1.65fr_.85fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-950">Hàng đợi ưu tiên</h2><p className="mt-1 text-xs text-slate-500">Sắp xếp theo SLA, trạng thái và lịch hẹn</p></div><Link to="/service-requests" className="text-xs font-bold text-blue-600">Xem tất cả</Link></div><div className="divide-y divide-slate-100">{queue.length ? queue.map(request => <Link key={request.id} to={`/service-requests/${request.id}`} className="grid gap-3 p-4 transition hover:bg-blue-50/50 md:grid-cols-[1fr_150px_130px] md:items-center"><div className="flex min-w-0 items-start gap-3"><span className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${request.status === 'pending' ? 'bg-amber-50 text-amber-600' : 'bg-blue-50 text-blue-600'}`}><Wrench className="h-5 w-5" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-slate-900">{request.customerName}</strong><span className="text-xs font-semibold text-blue-600">{request.id}</span></div><p className="mt-1 truncate text-xs text-slate-500">{request.applianceType} · {request.issueDescription}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><MapPin className="h-3 w-3" />{request.district}</p></div></div><ServiceRequestStatusBadge status={request.status} /><ServiceRequestSlaBadge status={request.status} preferredDate={request.preferredDate} todayStr={today} tomorrowStr={tomorrow} createdAt={request.createdAt} nowMs={nowMs} /></Link>) : <div className="p-10 text-center text-sm text-slate-400">Không có yêu cầu đang chờ xử lý.</div>}</div></section>
      <aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-xl shadow-slate-900/10"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-cyan-300"><TrendingUp className="h-5 w-5" /></span><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">{confirmationRate}%</span></div><h2 className="mt-5 text-lg font-bold">Tỷ lệ đã tiếp nhận</h2><p className="mt-2 text-sm leading-6 text-slate-400">Tỷ lệ yêu cầu đã được xử lý khỏi trạng thái chờ xác nhận.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400 transition-all duration-700" style={{ width: `${confirmationRate}%` }} /></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">Năng lực đội thợ</h2><div className="mt-5 grid grid-cols-2 gap-3"><MiniStat icon={UserCheck} value={availableTechs} label="Sẵn sàng" /><MiniStat icon={Wrench} value={technicians.filter(item => item.status === 'busy').length} label="Đang bận" /><MiniStat icon={CalendarCheck} value={technicians.length} label="Tổng thợ" /><MiniStat icon={CheckCircle2} value={technicians.reduce((sum, item) => sum + Number(item.completedCount || 0), 0)} label="Việc hoàn tất" /></div></section></aside></div>
  </div>;
}
function urgencyScore(request: ServiceRequest, nowMs: number) { let score = request.status === 'pending' ? 100 : request.status === 'confirmed' && !request.assignedTechnicianId ? 80 : 40; score += Math.min(100, (nowMs - new Date(request.createdAt).getTime()) / 60000); if (request.priority === 'urgent') score += 100; if (request.priority === 'high') score += 50; return score; }
function Kpi({ icon: Icon, tone, label, value, detail }: { icon: typeof Clock3; tone: string; label: string; value: number; detail: string }) { const classes: Record<string, string> = { amber: 'bg-amber-50 text-amber-600', blue: 'bg-blue-50 text-blue-600', cyan: 'bg-cyan-50 text-cyan-600', emerald: 'bg-emerald-50 text-emerald-600' }; return <div className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-900/5"><div className="flex items-start justify-between"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${classes[tone]}`}><Icon className="h-5 w-5" /></span><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-500" /></div><p className="mt-5 text-sm font-semibold text-slate-500">{label}</p><strong className="mt-1 block text-3xl font-bold tracking-tight text-slate-950">{value}</strong><p className="mt-2 text-xs text-slate-400">{detail}</p></div>; }
function MiniStat({ icon: Icon, value, label }: { icon: typeof Wrench; value: number; label: string }) { return <div className="rounded-xl bg-slate-50 p-3"><Icon className="h-4 w-4 text-blue-600" /><strong className="mt-2 block text-xl text-slate-950">{value}</strong><span className="text-xs text-slate-500">{label}</span></div>; }
