import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Banknote, CircleDollarSign, Download, FileClock, HandCoins, PackageOpen, PencilLine, ReceiptText, TrendingUp, UsersRound, WalletCards, X } from 'lucide-react';
import api from '../services/api';

type FinanceRequest = { id: string; completedAt: string; customerName: string; applianceType: string; technicianName: string; revenue: number; collected: number; debt: number; partsCost: number; technicianPay: number; estimatedProfit: number; paymentStatus: string; settlementStatus: string };
type GroupRow = { id: string; label: string; jobs: number; revenue: number; collected: number; technicianPay: number; estimatedProfit: number };
type Report = { month: string; recognitionPolicy: string; totals: { jobs: number; revenue: number; collected: number; debt: number; partsCost: number; technicianPay: number; estimatedProfit: number }; byDay: { date: string; revenue: number; collected: number; jobs: number }[]; byTechnician: GroupRow[]; byService: GroupRow[]; requests: FinanceRequest[]; generatedAt: string };
type AuditEntry = { id: string; requestId: string; action: string; actorName: string; note?: string; createdAt: string };

const money = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value || 0);
const currentMonth = new Date().toISOString().slice(0, 7);

export default function Finance() {
  const [month, setMonth] = useState(currentMonth);
  const [tab, setTab] = useState<'overview' | 'settlement' | 'audit'>('overview');
  const [editing, setEditing] = useState<FinanceRequest | null>(null);
  const [message, setMessage] = useState('');
  const queryClient = useQueryClient();
  const reportQuery = useQuery({ queryKey: ['finance-report', month], queryFn: async () => (await api.get('/admin/finance/report', { params: { month } })).data.data as Report });
  const auditQuery = useQuery({ queryKey: ['finance-audit', month], queryFn: async () => (await api.get('/admin/finance/audit-logs', { params: { month } })).data.data as AuditEntry[], enabled: tab === 'audit' });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['finance-report', month] }); queryClient.invalidateQueries({ queryKey: ['finance-audit', month] }); };
  const update = useMutation({ mutationFn: ({ id, data }: { id: string; data: unknown }) => api.patch(`/admin/finance/requests/${id}`, data), onSuccess: response => { setEditing(null); setMessage(response.data.message); refresh(); }, onError: () => setMessage('Không thể cập nhật số liệu. Vui lòng kiểm tra lại.') });
  const settle = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api.patch(`/admin/finance/requests/${id}/settlement`, { status }), onSuccess: response => { setMessage(response.data.message); refresh(); } });
  const report = reportQuery.data;
  const maxDaily = useMemo(() => Math.max(1, ...(report?.byDay.map(item => item.revenue) || [1])), [report]);

  const exportExcel = async () => {
    const response = await api.get('/admin/finance/export', { params: { month }, responseType: 'blob' });
    const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `doi-soat-${month}.xls`; anchor.click(); URL.revokeObjectURL(url);
  };

  if (reportQuery.isLoading) return <div className="flex h-72 items-center justify-center text-sm font-medium text-slate-400">Đang tổng hợp số liệu dịch vụ...</div>;
  if (!report) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">Không thể tải báo cáo tài chính.</div>;

  return <div className="mx-auto max-w-[1500px] space-y-6 pb-10">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700"><TrendingUp className="h-3.5 w-3.5" />Tài chính dịch vụ</div><h2 className="text-2xl font-black tracking-tight text-slate-950">Doanh thu & đối soát</h2><p className="mt-1 text-sm text-slate-500">Số liệu chỉ lấy từ yêu cầu sửa chữa đã hoàn thành, không bao gồm bán sản phẩm.</p></div><div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600">Kỳ báo cáo<input type="month" value={month} max={currentMonth} onChange={event => setMonth(event.target.value)} className="h-10 bg-transparent outline-none" /></label><button onClick={exportExcel} className="flex h-11 items-center gap-2 rounded-xl bg-emerald-600 px-4 text-xs font-bold text-white shadow-lg shadow-emerald-600/15 transition hover:-translate-y-0.5 hover:bg-emerald-700"><Download className="h-4 w-4" />Xuất Excel</button></div></div>
    {message && <div className="flex items-center justify-between rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700"><span>{message}</span><button onClick={() => setMessage('')} aria-label="Đóng"><X className="h-4 w-4" /></button></div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={CircleDollarSign} label="Doanh thu" value={money(report.totals.revenue)} tone="blue" /><Metric icon={WalletCards} label="Đã thu" value={money(report.totals.collected)} tone="emerald" /><Metric icon={FileClock} label="Công nợ" value={money(report.totals.debt)} tone="amber" /><Metric icon={UsersRound} label="Công thợ" value={money(report.totals.technicianPay)} tone="violet" /><Metric icon={PackageOpen} label="Linh kiện" value={money(report.totals.partsCost)} tone="orange" /><Metric icon={TrendingUp} label="Lợi nhuận tạm tính" value={money(report.totals.estimatedProfit)} tone="cyan" /></div>
    <div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1.5">{([['overview', 'Tổng quan'], ['settlement', 'Đối soát thợ'], ['audit', 'Nhật ký chỉnh sửa']] as const).map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-xs font-bold transition ${tab === id ? 'bg-slate-950 text-white shadow' : 'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</div>
    {tab === 'overview' && <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-extrabold text-slate-900">Dòng tiền theo ngày</h3><p className="mt-1 text-xs text-slate-400">Doanh thu và tiền thực thu trong kỳ</p></div><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-500">{report.totals.jobs} công việc</span></div><div className="mt-7 flex h-52 items-end gap-2 overflow-x-auto border-b border-slate-100 pb-1">{report.byDay.length ? report.byDay.map(item => <div key={item.date} className="group flex min-w-12 flex-1 flex-col items-center justify-end gap-1"><div className="relative flex h-40 w-full max-w-12 items-end justify-center gap-1"><div title={`Doanh thu ${money(item.revenue)}`} style={{ height: `${Math.max(4, item.revenue / maxDaily * 100)}%` }} className="w-3 rounded-t bg-blue-500 transition-all group-hover:bg-blue-600" /><div title={`Đã thu ${money(item.collected)}`} style={{ height: `${Math.max(3, item.collected / maxDaily * 100)}%` }} className="w-3 rounded-t bg-emerald-400 transition-all group-hover:bg-emerald-500" /></div><span className="text-[10px] font-semibold text-slate-400">{item.date.slice(8)}</span></div>) : <div className="m-auto text-center text-sm text-slate-400">Chưa có công việc hoàn thành trong tháng này.</div>}</div><div className="mt-4 flex gap-5 text-[11px] font-semibold text-slate-500"><span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-sm bg-blue-500" />Doanh thu</span><span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-sm bg-emerald-400" />Đã thu</span></div></section><div className="grid gap-6 xl:grid-cols-2"><Ranking title="Doanh thu theo thợ" rows={report.byTechnician} icon={<UsersRound className="h-5 w-5" />} /><Ranking title="Doanh thu theo dịch vụ" rows={report.byService} icon={<ReceiptText className="h-5 w-5" />} /></div></div>}
    {tab === 'settlement' && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="font-extrabold text-slate-900">Đối soát từng công việc</h3><p className="mt-1 text-xs text-slate-400">Cập nhật tiền đã thu, linh kiện và trạng thái thanh toán tiền công thợ.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr>{['Yêu cầu', 'Khách / dịch vụ', 'Kỹ thuật viên', 'Doanh thu', 'Đã thu / nợ', 'Linh kiện', 'Công thợ', 'Đối soát', ''].map(value => <th key={value} className="px-4 py-3 font-bold">{value}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{report.requests.map(item => <tr key={item.id} className="hover:bg-slate-50/70"><td className="px-4 py-4"><strong className="text-blue-600">{item.id}</strong><p className="mt-1 text-slate-400">{new Date(item.completedAt).toLocaleDateString('vi-VN')}</p></td><td className="px-4 py-4"><strong className="text-slate-800">{item.customerName}</strong><p className="mt-1 text-slate-400">{item.applianceType}</p></td><td className="px-4 py-4 font-semibold text-slate-600">{item.technicianName}</td><td className="px-4 py-4 font-bold text-slate-900">{money(item.revenue)}</td><td className="px-4 py-4"><span className="font-bold text-emerald-600">{money(item.collected)}</span><p className="mt-1 text-amber-600">Nợ {money(item.debt)}</p></td><td className="px-4 py-4">{money(item.partsCost)}</td><td className="px-4 py-4 font-semibold text-violet-600">{money(item.technicianPay)}</td><td className="px-4 py-4"><button disabled={settle.isPending} onClick={() => settle.mutate({ id: item.id, status: item.settlementStatus === 'settled' ? 'pending' : 'settled' })} className={`rounded-full px-3 py-1.5 font-bold ${item.settlementStatus === 'settled' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{item.settlementStatus === 'settled' ? 'Đã đối soát' : 'Chờ đối soát'}</button></td><td className="px-4 py-4"><button onClick={() => setEditing(item)} className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:border-blue-200 hover:text-blue-600" aria-label={`Chỉnh sửa ${item.id}`}><PencilLine className="h-4 w-4" /></button></td></tr>)}</tbody></table>{!report.requests.length && <div className="p-12 text-center text-sm text-slate-400">Chưa có dữ liệu để đối soát.</div>}</div></section>}
    {tab === 'audit' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-extrabold text-slate-900">Nhật ký tài chính</h3><div className="mt-5 space-y-3">{auditQuery.data?.map(item => <div key={item.id} className="flex gap-3 rounded-xl border border-slate-100 p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><FileClock className="h-4 w-4" /></span><div><p className="text-sm font-bold text-slate-800">{item.action === 'UPDATE_SETTLEMENT' ? 'Thay đổi đối soát' : 'Cập nhật tài chính'} · {item.requestId}</p><p className="mt-1 text-xs text-slate-500">{item.actorName} · {new Date(item.createdAt).toLocaleString('vi-VN')}</p>{item.note && <p className="mt-1 text-xs text-slate-400">{item.note}</p>}</div></div>)}{!auditQuery.data?.length && <div className="p-10 text-center text-sm text-slate-400">Chưa có chỉnh sửa tài chính trong kỳ.</div>}</div></section>}
    {editing && <FinanceModal item={editing} loading={update.isPending} onClose={() => setEditing(null)} onSave={data => update.mutate({ id: editing.id, data })} />}
  </div>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof Banknote; label: string; value: string; tone: string }) { const styles: Record<string, string> = { blue: 'bg-blue-50 text-blue-600', emerald: 'bg-emerald-50 text-emerald-600', amber: 'bg-amber-50 text-amber-600', violet: 'bg-violet-50 text-violet-600', orange: 'bg-orange-50 text-orange-600', cyan: 'bg-cyan-50 text-cyan-600' }; return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${styles[tone]}`}><Icon className="h-4 w-4" /></span><p className="mt-4 text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</p><strong className="mt-1 block text-lg text-slate-950">{value}</strong></div>; }
function Ranking({ title, rows, icon }: { title: string; rows: GroupRow[]; icon: React.ReactNode }) { const max = Math.max(1, ...rows.map(item => item.revenue)); return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-slate-900">{icon}<h3 className="font-extrabold">{title}</h3></div><div className="mt-5 space-y-4">{rows.map((item, index) => <div key={item.id}><div className="mb-2 flex items-center justify-between gap-3"><span className="truncate text-sm font-semibold text-slate-700"><b className="mr-2 text-slate-300">#{index + 1}</b>{item.label}</span><span className="whitespace-nowrap text-sm font-bold text-slate-900">{money(item.revenue)}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400" style={{ width: `${item.revenue / max * 100}%` }} /></div><p className="mt-1.5 text-[10px] text-slate-400">{item.jobs} việc · Lợi nhuận {money(item.estimatedProfit)}</p></div>)}{!rows.length && <p className="py-8 text-center text-sm text-slate-400">Chưa có dữ liệu.</p>}</div></section>; }
function FinanceModal({ item, loading, onClose, onSave }: { item: FinanceRequest; loading: boolean; onClose: () => void; onSave: (data: unknown) => void }) { const [partsCost, setPartsCost] = useState(item.partsCost); const [amountCollected, setAmountCollected] = useState(item.collected); const [paymentStatus, setPaymentStatus] = useState(item.paymentStatus); const [note, setNote] = useState(''); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && onClose()}><form onSubmit={event => { event.preventDefault(); onSave({ partsCost, amountCollected, paymentStatus, note }); }} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-blue-600">{item.id}</p><h3 className="mt-1 text-xl font-black text-slate-950">Cập nhật tài chính</h3></div><button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100"><X className="h-4 w-4" /></button></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><span className="text-slate-500">Doanh thu cuối cùng</span><strong className="float-right text-slate-950">{money(item.revenue)}</strong></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Chi phí linh kiện"><input type="number" min="0" value={partsCost} onChange={event => setPartsCost(Number(event.target.value))} className="finance-input" /></Field><Field label="Số tiền đã thu"><input type="number" min="0" max={item.revenue} value={amountCollected} onChange={event => setAmountCollected(Number(event.target.value))} className="finance-input" /></Field></div><Field label="Trạng thái thanh toán"><select value={paymentStatus} onChange={event => { const status = event.target.value; setPaymentStatus(status); if (status === 'paid') setAmountCollected(item.revenue); if (status === 'unpaid') setAmountCollected(0); }} className="finance-input"><option value="unpaid">Chưa thu</option><option value="partial">Thu một phần</option><option value="paid">Đã thu đủ</option></select></Field><Field label="Ghi chú chỉnh sửa"><textarea value={note} onChange={event => setNote(event.target.value)} rows={3} className="finance-input h-auto py-3" placeholder="Lý do hoặc chứng từ liên quan..." /></Field><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="h-11 rounded-xl px-4 text-sm font-bold text-slate-500">Hủy</button><button disabled={loading} className="flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white disabled:opacity-50"><HandCoins className="h-4 w-4" />{loading ? 'Đang lưu...' : 'Lưu số liệu'}</button></div></form></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block text-xs font-bold text-slate-600">{label}<div className="mt-2">{children}</div></label>; }
