CREATE TABLE `NotificationOutbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `eventType` VARCHAR(100) NOT NULL,
  `channel` ENUM('EMAIL','ADMIN','SMS','ZALO') NOT NULL,
  `recipient` VARCHAR(255) NULL,
  `subject` VARCHAR(255) NULL,
  `templateKey` VARCHAR(100) NOT NULL,
  `payload` JSON NOT NULL,
  `status` ENUM('PENDING','PROCESSING','SENT','FAILED','DEAD') NOT NULL DEFAULT 'PENDING',
  `attempts` INT NOT NULL DEFAULT 0,
  `maxAttempts` INT NOT NULL DEFAULT 5,
  `nextAttemptAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lockedAt` DATETIME(3) NULL,
  `lockedBy` VARCHAR(100) NULL,
  `sentAt` DATETIME(3) NULL,
  `lastErrorCode` VARCHAR(100) NULL,
  `lastErrorMessage` VARCHAR(500) NULL,
  `correlationId` VARCHAR(100) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NotificationOutbox_idempotencyKey_key` (`idempotencyKey`),
  INDEX `NotificationOutbox_dispatch_idx` (`status`, `nextAttemptAt`),
  INDEX `NotificationOutbox_event_idx` (`eventType`, `createdAt`),
  INDEX `NotificationOutbox_correlation_idx` (`correlationId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `AdminNotification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dedupeKey` VARCHAR(191) NOT NULL,
  `type` VARCHAR(80) NOT NULL,
  `severity` ENUM('INFO','SUCCESS','WARNING','CRITICAL') NOT NULL DEFAULT 'INFO',
  `title` VARCHAR(255) NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  `actionUrl` VARCHAR(500) NULL,
  `entityType` VARCHAR(80) NULL,
  `entityId` VARCHAR(100) NULL,
  `isRead` BOOLEAN NOT NULL DEFAULT false,
  `readAt` DATETIME(3) NULL,
  `expiresAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `AdminNotification_dedupeKey_key` (`dedupeKey`),
  INDEX `AdminNotification_feed_idx` (`isRead`, `createdAt`),
  INDEX `AdminNotification_entity_idx` (`entityType`, `entityId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `IntegrationDeliveryLog` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `outboxId` BIGINT NULL,
  `provider` VARCHAR(80) NOT NULL,
  `channel` VARCHAR(30) NOT NULL,
  `success` BOOLEAN NOT NULL,
  `attempt` INT NOT NULL,
  `durationMs` INT NOT NULL,
  `responseCode` VARCHAR(100) NULL,
  `errorCode` VARCHAR(100) NULL,
  `errorMessage` VARCHAR(500) NULL,
  `correlationId` VARCHAR(100) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `IntegrationDeliveryLog_outbox_idx` (`outboxId`, `createdAt`),
  INDEX `IntegrationDeliveryLog_provider_idx` (`provider`, `success`, `createdAt`),
  CONSTRAINT `IntegrationDeliveryLog_outbox_fkey` FOREIGN KEY (`outboxId`) REFERENCES `NotificationOutbox`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;