import { Body,Controller,Get,Headers,Param,Post,Req,UnauthorizedException,UseGuards } from '@nestjs/common'; import { UserRole } from '@prisma/client'; import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard'; import { RolesGuard } from '../../common/guards/roles.guard'; import { Roles } from '../../common/decorators/roles.decorator'; import { CustomerVerificationService } from '../customer-verification/customer-verification.service'; import { PhoneQuoteDecisionDto,QuoteDecisionDto,RecordPaymentDto } from './service-quotes.dto'; import { ServiceQuotesService } from './service-quotes.service';
@Controller() export class ServiceQuotesController {constructor(private quotes:ServiceQuotesService,private lookup:CustomerVerificationService){}
 @UseGuards(JwtAuthGuard,RolesGuard) @Roles(UserRole.STAFF,UserRole.ADMIN,UserRole.SUPERADMIN) @Get('admin/service-requests/:id/quotes') list(@Param('id')id:string){return this.quotes.list(id)}
 @UseGuards(JwtAuthGuard,RolesGuard) @Roles(UserRole.STAFF,UserRole.ADMIN,UserRole.SUPERADMIN) @Post('admin/service-quotes/:id/send') send(@Param('id')id:string){return this.quotes.send(id)}
 @UseGuards(JwtAuthGuard) @Post('me/service-quotes/:id/decision') customer(@Param('id')id:string,@Body()dto:QuoteDecisionDto,@Req()req:any){return this.quotes.decideCustomer(id,req.user.userId,dto.decision,dto.evidence)}
 @UseGuards(JwtAuthGuard) @Get('me/service-requests/:id/quote') customerQuote(@Param('id')id:string,@Req()req:any){return this.quotes.listCustomer(id,req.user.userId)}
 @Post('service-quotes/:id/guest-decision') async guest(@Param('id')id:string,@Body()dto:QuoteDecisionDto,@Headers('authorization')auth?:string){const token=auth?.startsWith('Lookup ')?auth.slice(7):'';const quote=(await this.quotes.listForLookup(id));if(!await this.lookup.authorizeLookup(quote.serviceRequestId,token))throw new UnauthorizedException();return this.quotes.decideGuest(id,dto.decision,dto.evidence)}
 @UseGuards(JwtAuthGuard,RolesGuard) @Roles(UserRole.ADMIN,UserRole.SUPERADMIN) @Post('admin/service-quotes/:id/phone-decision') phone(@Param('id')id:string,@Body()dto:PhoneQuoteDecisionDto,@Req()req:any){return this.quotes.decidePhone(id,dto.decision,String(req.user.userId),dto.note)}
 @UseGuards(JwtAuthGuard,RolesGuard) @Roles(UserRole.ADMIN,UserRole.SUPERADMIN) @Post('admin/service-requests/:id/payments') payment(@Param('id')id:string,@Body()dto:RecordPaymentDto,@Req()req:any){return this.quotes.recordPayment(id,dto.amount,dto.method,dto.reference,String(req.user.userId))}
}
