import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../../core/database/prisma.service';
@Injectable() export class ServiceQuotesService { constructor(private prisma:PrismaService){}
 async listForLookup(id:string){const quote=await this.prisma.serviceQuote.findUnique({where:{id},select:{serviceRequestId:true}});if(!quote)throw new NotFoundException('Không tìm thấy báo giá');return quote;}
 async listCustomer(requestId:string,userId:number){const request=await this.prisma.serviceRequest.findFirst({where:{id:requestId,userId}});if(!request)throw new ForbiddenException();const quote=await this.prisma.serviceQuote.findFirst({where:{serviceRequestId:requestId,status:{in:['sent','approved','rejected']}},include:{approvals:true},orderBy:{version:'desc'}});return{success:true,data:quote};}
 async list(requestId:string){const quotes=await this.prisma.serviceQuote.findMany({where:{serviceRequestId:requestId},include:{approvals:true},orderBy:{version:'desc'}});return{success:true,data:quotes};}
 async send(id:string){const quote=await this.prisma.serviceQuote.findUnique({where:{id}});if(!quote)throw new NotFoundException('Không tìm thấy báo giá');if(quote.status!=='draft')throw new BadRequestException('Chỉ có thể gửi báo giá nháp');return this.prisma.$transaction(async tx=>{const sent=await tx.serviceQuote.update({where:{id},data:{status:'sent'}});await tx.serviceRequest.update({where:{id:quote.serviceRequestId},data:{status:'waiting_customer_approval' as any}});return{success:true,data:sent};});}
 private async decide(id:string,decision:'approved'|'rejected',actorType:string,actorId:string|undefined,channel:string,evidence?:string){const quote=await this.prisma.serviceQuote.findUnique({where:{id},include:{serviceRequest:true}});if(!quote)throw new NotFoundException('Không tìm thấy báo giá');const latest=await this.prisma.serviceQuote.findFirst({where:{serviceRequestId:quote.serviceRequestId},orderBy:{version:'desc'}});if(!latest||latest.id!==quote.id||quote.status!=='sent'||quote.validUntil<=new Date())throw new BadRequestException('Báo giá không còn hiệu lực');const result=await this.prisma.$transaction(async tx=>{const approval=await tx.quoteApproval.create({data:{quoteId:id,version:quote.version,decision,actorType,actorId,channel,evidence}});await tx.serviceQuote.update({where:{id},data:{status:decision}});if(decision==='approved')await tx.serviceRequest.update({where:{id:quote.serviceRequestId},data:{status:'in_progress' as any}});return approval;});return{success:true,data:result};}
 async decideCustomer(id:string,userId:number,decision:'approved'|'rejected',evidence?:string){const quote=await this.prisma.serviceQuote.findUnique({where:{id},include:{serviceRequest:true}});if(!quote||quote.serviceRequest.userId!==userId)throw new ForbiddenException();return this.decide(id,decision,'customer',String(userId),'account',evidence);}
 decideGuest(id:string,decision:'approved'|'rejected',evidence?:string){return this.decide(id,decision,'guest',undefined,'lookup_token',evidence);}
 decidePhone(id:string,decision:'approved'|'rejected',actorId:string,note:string){return this.decide(id,decision,'staff',actorId,'phone',note);}

}
