import { useState } from 'react';
import { Calculator, Clock3, MapPin, Plus, ShieldCheck, Trash2, Users, Wrench } from 'lucide-react';
import type { BusinessConfig } from '../../../types/businessConfig';

interface Props { value: BusinessConfig; onChange: (value: BusinessConfig) => void; }
type Tab = 'appliances' | 'areas' | 'schedules' | 'workflow' | 'finance';
const tabs: { id: Tab; label: string; icon: typeof Wrench }[] = [
  { id: 'appliances', label: 'Thiết bị & khoảng giá', icon: Wrench },
  { id: 'areas', label: 'Khu vực phục vụ', icon: MapPin },
  { id: 'schedules', label: 'Khung giờ & phí', icon: Clock3 },
  { id: 'workflow', label: 'Quy trình & vai trò', icon: ShieldCheck },
  { id: 'finance', label: 'Doanh thu & tiền công', icon: Calculator },
];
const slugify = (text: string) => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || `item-${Date.now()}`;
const money = new Intl.NumberFormat('vi-VN');
const inputClass = 'h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10';

export default function BusinessConfigEditor({ value, onChange }: Props) {
  const [tab, setTab] = useState<Tab>('appliances');
  const set = <K extends keyof BusinessConfig>(key: K, next: BusinessConfig[K]) => onChange({ ...value, [key]: next });

  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-200 bg-slate-50/70 p-2">
      <div className="flex gap-1 overflow-x-auto" role="tablist" aria-label="Nhóm cấu hình nghiệp vụ">
        {tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-semibold transition ${tab === id ? 'bg-white text-blue-700 shadow-sm ring-1 ring-slate-200' : 'text-slate-500 hover:bg-white/70 hover:text-slate-800'}`}><Icon className="h-4 w-4" />{label}</button>)}
      </div>
    </div>
    <div className="p-5 md:p-7">
      {tab === 'appliances' && <Appliances value={value} set={set} />}
      {tab === 'areas' && <Areas value={value} set={set} />}
      {tab === 'schedules' && <Schedules value={value} onChange={onChange} set={set} />}
      {tab === 'workflow' && <Workflow value={value} set={set} />}
      {tab === 'finance' && <Finance value={value} onChange={onChange} />}
    </div>
  </div>;
}

function Heading({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) {
  return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-lg font-bold text-slate-950">{title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>{action}</div>;
}
function AddButton({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button type="button" onClick={onClick} className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white shadow-sm transition hover:bg-blue-700"><Plus className="h-4 w-4" />{children}</button>; }
function Toggle({ checked, onChange, label = 'Đang hoạt động' }: { checked: boolean; onChange: (checked: boolean) => void; label?: string }) { return <label className="inline-flex cursor-pointer items-center gap-2 text-sm font-medium text-slate-600"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} className="h-4 w-4 rounded border-slate-300 text-blue-600" />{label}</label>; }
function Remove({ onClick, label }: { onClick: () => void; label: string }) { return <button type="button" onClick={onClick} aria-label={label} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-slate-400 transition hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button>; }

function Appliances({ value, set }: { value: BusinessConfig; set: <K extends keyof BusinessConfig>(key: K, next: BusinessConfig[K]) => void }) {
  const update = (index: number, patch: Partial<BusinessConfig['appliances'][number]>) => set('appliances', value.appliances.map((x, i) => i === index ? { ...x, ...patch } : x));
  return <><Heading title="Danh sách thiết bị và lỗi phổ biến" description="Những mục đang hoạt động sẽ xuất hiện trong form đặt lịch. Khoảng giá chỉ mang tính tham khảo và không phải báo giá chính thức." action={<AddButton onClick={() => set('appliances', [...value.appliances, { id: `device-${Date.now()}`, name: 'Thiết bị mới', active: true, issues: ['Không rõ lỗi'], priceMin: 0, priceMax: 0 }])}>Thêm thiết bị</AddButton>} />
    <div className="space-y-4">{value.appliances.map((item, index) => <div key={item.id} className="rounded-2xl border border-slate-200 p-4 transition hover:border-blue-200 md:p-5">
      <div className="flex items-start gap-3"><div className="grid flex-1 gap-4 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Tên thiết bị<input className={`${inputClass} mt-1.5`} value={item.name} onChange={e => update(index, { name: e.target.value, id: item.id.startsWith('device-') ? slugify(e.target.value) : item.id })} /></label><label className="text-xs font-semibold text-slate-600">Mã hệ thống<input className={`${inputClass} mt-1.5 bg-slate-50`} value={item.id} onChange={e => update(index, { id: slugify(e.target.value) })} /></label></div><Remove label={`Xóa ${item.name}`} onClick={() => set('appliances', value.appliances.filter((_, i) => i !== index))} /></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Giá thấp nhất (VNĐ)<input type="number" min="0" className={`${inputClass} mt-1.5`} value={item.priceMin} onChange={e => update(index, { priceMin: Number(e.target.value) })} /></label><label className="text-xs font-semibold text-slate-600">Giá cao nhất (VNĐ)<input type="number" min="0" className={`${inputClass} mt-1.5`} value={item.priceMax} onChange={e => update(index, { priceMax: Number(e.target.value) })} /></label></div>
      <label className="mt-4 block text-xs font-semibold text-slate-600">Lỗi phổ biến <span className="font-normal text-slate-400">(mỗi lỗi một dòng)</span><textarea rows={3} className={`${inputClass} mt-1.5 h-auto py-3`} value={item.issues.join('\n')} onChange={e => update(index, { issues: e.target.value.split('\n').map(x => x.trim()).filter(Boolean) })} /></label>
      <div className="mt-4 flex items-center justify-between"><Toggle checked={item.active} onChange={active => update(index, { active })} /><span className="text-xs text-slate-400">{money.format(item.priceMin)}đ – {money.format(item.priceMax)}đ</span></div>
    </div>)}</div></>;
}

function Areas({ value, set }: { value: BusinessConfig; set: <K extends keyof BusinessConfig>(key: K, next: BusinessConfig[K]) => void }) {
  const update = (index: number, patch: Partial<BusinessConfig['serviceAreas'][number]>) => set('serviceAreas', value.serviceAreas.map((x, i) => i === index ? { ...x, ...patch } : x));
  return <><Heading title="Khu vực phục vụ" description="Quản lý quận/huyện khách hàng có thể chọn và phí di chuyển tham khảo tại từng khu vực." action={<AddButton onClick={() => set('serviceAreas', [...value.serviceAreas, { id: `area-${Date.now()}`, name: 'Khu vực mới', active: true, travelFee: 0 }])}>Thêm khu vực</AddButton>} /><div className="overflow-hidden rounded-xl border border-slate-200"><div className="hidden grid-cols-[1.5fr_1fr_140px_44px] gap-3 bg-slate-50 px-4 py-3 text-xs font-bold uppercase tracking-wide text-slate-500 md:grid"><span>Khu vực</span><span>Phí di chuyển</span><span>Trạng thái</span><span /></div>{value.serviceAreas.map((item, index) => <div key={item.id} className="grid gap-3 border-t border-slate-100 p-4 first:border-t-0 md:grid-cols-[1.5fr_1fr_140px_44px] md:items-center"><input className={inputClass} value={item.name} onChange={e => update(index, { name: e.target.value, id: item.id.startsWith('area-') ? slugify(e.target.value) : item.id })} /><input type="number" min="0" className={inputClass} value={item.travelFee} onChange={e => update(index, { travelFee: Number(e.target.value) })} /><Toggle checked={item.active} onChange={active => update(index, { active })} label={item.active ? 'Đang phục vụ' : 'Tạm ẩn'} /><Remove label={`Xóa ${item.name}`} onClick={() => set('serviceAreas', value.serviceAreas.filter((_, i) => i !== index))} /></div>)}</div></>;
}

function Schedules({ value, onChange, set }: { value: BusinessConfig; onChange: (v: BusinessConfig) => void; set: <K extends keyof BusinessConfig>(key: K, next: BusinessConfig[K]) => void }) {
  const update = (index: number, patch: Partial<BusinessConfig['timeSlots'][number]>) => set('timeSlots', value.timeSlots.map((x, i) => i === index ? { ...x, ...patch } : x));
  return <><Heading title="Khung giờ tiếp nhận" description="Các khung giờ đang hoạt động sẽ được dùng trực tiếp trong form đặt lịch của khách hàng." action={<AddButton onClick={() => set('timeSlots', [...value.timeSlots, { id: `slot-${Date.now()}`, label: '18:00 - 20:00', active: true }])}>Thêm khung giờ</AddButton>} /><div className="grid gap-3 sm:grid-cols-2">{value.timeSlots.map((item, index) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input className={inputClass} value={item.label} onChange={e => update(index, { label: e.target.value })} /><Toggle checked={item.active} onChange={active => update(index, { active })} label="Hiện" /><Remove label={`Xóa ${item.label}`} onClick={() => set('timeSlots', value.timeSlots.filter((_, i) => i !== index))} /></div>)}</div>
    <div className="mt-8 border-t border-slate-200 pt-7"><Heading title="Nguyên tắc chi phí tham khảo" description="Cấu hình phí kiểm tra, phụ phí khẩn cấp và thông báo bắt buộc hiển thị cho khách." /><div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Phí kiểm tra mặc định (VNĐ)<input type="number" min="0" className={`${inputClass} mt-1.5`} value={value.pricing.inspectionFee} onChange={e => onChange({ ...value, pricing: { ...value.pricing, inspectionFee: Number(e.target.value) } })} /></label><label className="text-xs font-semibold text-slate-600">Phụ phí khẩn cấp (VNĐ)<input type="number" min="0" className={`${inputClass} mt-1.5`} value={value.pricing.emergencySurcharge} onChange={e => onChange({ ...value, pricing: { ...value.pricing, emergencySurcharge: Number(e.target.value) } })} /></label></div><label className="mt-4 block text-xs font-semibold text-slate-600">Thông báo giá tham khảo<textarea rows={3} className={`${inputClass} mt-1.5 h-auto py-3`} value={value.pricing.disclaimer} onChange={e => onChange({ ...value, pricing: { ...value.pricing, disclaimer: e.target.value } })} /></label><div className="mt-4"><Toggle checked={value.pricing.showPriceRanges} onChange={showPriceRanges => onChange({ ...value, pricing: { ...value.pricing, showPriceRanges } })} label="Hiển thị khoảng giá trên website khách hàng" /></div></div></>;
}

function Workflow({ value, set }: { value: BusinessConfig; set: <K extends keyof BusinessConfig>(key: K, next: BusinessConfig[K]) => void }) {
  const updateStatus = (i: number, patch: Partial<BusinessConfig['requestStatuses'][number]>) => set('requestStatuses', value.requestStatuses.map((x, j) => i === j ? { ...x, ...patch } : x));
  const updateRole = (i: number, patch: Partial<BusinessConfig['roles'][number]>) => set('roles', value.roles.map((x, j) => i === j ? { ...x, ...patch } : x));
  return <><Heading title="Trạng thái yêu cầu" description="Thứ tự dưới đây là quy trình chuẩn được dùng chung cho điều phối và kỹ thuật viên." action={<AddButton onClick={() => set('requestStatuses', [...value.requestStatuses, { id: `status-${Date.now()}`, label: 'Trạng thái mới', color: 'slate', active: true }])}>Thêm trạng thái</AddButton>} /><div className="space-y-2">{value.requestStatuses.map((item, i) => <div key={`${item.id}-${i}`} className="grid gap-3 rounded-xl border border-slate-200 p-3 md:grid-cols-[40px_1fr_1fr_120px_44px] md:items-center"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-500">{i + 1}</span><input className={inputClass} value={item.label} onChange={e => updateStatus(i, { label: e.target.value })} /><input className={`${inputClass} bg-slate-50`} value={item.id} onChange={e => updateStatus(i, { id: slugify(e.target.value) })} /><Toggle checked={item.active} onChange={active => updateStatus(i, { active })} label="Sử dụng" /><Remove label={`Xóa ${item.label}`} onClick={() => set('requestStatuses', value.requestStatuses.filter((_, j) => j !== i))} /></div>)}</div>
    <div className="mt-8 border-t border-slate-200 pt-7"><Heading title="Vai trò vận hành" description="Tài liệu hóa trách nhiệm của từng nhóm. Phân quyền kỹ thuật vẫn được bảo vệ tại API." action={<AddButton onClick={() => set('roles', [...value.roles, { id: `role-${Date.now()}`, name: 'Vai trò mới', description: '' }])}>Thêm vai trò</AddButton>} /><div className="grid gap-3 md:grid-cols-2">{value.roles.map((role, i) => <div key={`${role.id}-${i}`} className="rounded-xl border border-slate-200 p-4"><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Users className="h-5 w-5" /></span><div className="flex-1"><input className={inputClass} value={role.name} onChange={e => updateRole(i, { name: e.target.value })} /><textarea rows={2} className={`${inputClass} mt-3 h-auto py-3`} placeholder="Mô tả trách nhiệm" value={role.description} onChange={e => updateRole(i, { description: e.target.value })} /></div><Remove label={`Xóa ${role.name}`} onClick={() => set('roles', value.roles.filter((_, j) => j !== i))} /></div></div>)}</div></div></>;
}

function Finance({ value, onChange }: { value: BusinessConfig; onChange: (v: BusinessConfig) => void }) {
  const patch = (next: Partial<BusinessConfig['finance']>) => onChange({ ...value, finance: { ...value.finance, ...next } });
  return <><Heading title="Quy tắc doanh thu và tiền công thợ" description="Đây là chuẩn nghiệp vụ dùng cho báo cáo. Chỉ chủ cửa hàng nên có quyền thay đổi các thông số này." /><div className="grid gap-5 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Thời điểm ghi nhận doanh thu<select className={`${inputClass} mt-1.5`} value={value.finance.revenueRecognition} onChange={e => patch({ revenueRecognition: e.target.value as 'completed' | 'paid' })}><option value="completed">Khi công việc hoàn thành</option><option value="paid">Khi đã nhận thanh toán</option></select><span className="mt-2 block font-normal leading-5 text-slate-400">Khuyến nghị: ghi nhận khi hoàn thành, theo dõi tiền đã thu riêng.</span></label><label className="text-xs font-semibold text-slate-600">Cách tính tiền công<select className={`${inputClass} mt-1.5`} value={value.finance.technicianPayType} onChange={e => patch({ technicianPayType: e.target.value as 'percentage' | 'fixed' })}><option value="percentage">Phần trăm doanh thu</option><option value="fixed">Mức cố định mỗi công việc</option></select></label><label className="text-xs font-semibold text-slate-600">{value.finance.technicianPayType === 'percentage' ? 'Tỷ lệ mặc định (%)' : 'Mức tiền công mặc định (VNĐ)'}<input type="number" min="0" max={value.finance.technicianPayType === 'percentage' ? 100 : undefined} className={`${inputClass} mt-1.5`} value={value.finance.technicianPayRate} onChange={e => patch({ technicianPayRate: Number(e.target.value) })} /></label><div className="flex items-end pb-3"><Toggle checked={value.finance.includePartsInCommission} onChange={includePartsInCommission => patch({ includePartsInCommission })} label="Tính cả chi phí linh kiện vào tiền công" /></div></div><div className="mt-7 rounded-2xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-bold text-blue-950">Công thức đang áp dụng</h3><p className="mt-2 text-sm leading-6 text-blue-800">Doanh thu được ghi nhận khi <strong>{value.finance.revenueRecognition === 'completed' ? 'công việc hoàn thành' : 'khách đã thanh toán'}</strong>. Tiền công thợ được tính theo <strong>{value.finance.technicianPayType === 'percentage' ? `${value.finance.technicianPayRate}% doanh thu` : `${money.format(value.finance.technicianPayRate)}đ mỗi công việc`}</strong>{value.finance.includePartsInCommission ? ', bao gồm phần linh kiện.' : ', không bao gồm phần linh kiện.'}</p></div></>;
}
