import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Eye, EyeOff, LockKeyhole, Phone, ShieldCheck, Wrench } from 'lucide-react';
import technicianApi from '../services/technicianApi';
export default function TechnicianLogin() {
  const navigate = useNavigate(); const [phone, setPhone] = useState(''); const [pin, setPin] = useState(''); const [showPin, setShowPin] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await technicianApi.post('/technician/auth/login', { phone, pin }); localStorage.setItem('dl247_technician_token', response.data.data.token); localStorage.setItem('dl247_technician', JSON.stringify(response.data.data.technician)); navigate('/technician', { replace: true }); } catch { setError('Số điện thoại hoặc mã PIN không chính xác.'); } finally { setLoading(false); } };
  return <main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-md"><div className="mb-8 text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 shadow-xl shadow-blue-500/20"><Wrench className="h-8 w-8" /></span><h1 className="mt-5 text-2xl font-bold">Cổng kỹ thuật viên</h1><p className="mt-2 text-sm text-slate-400">Nhận việc và cập nhật tiến độ ngay trên điện thoại</p></div><form onSubmit={submit} className="rounded-3xl border border-white/10 bg-white p-6 text-slate-900 shadow-2xl sm:p-8"><div className="mb-6 flex items-center gap-3 rounded-2xl bg-blue-50 p-4"><ShieldCheck className="h-5 w-5 text-blue-600" /><p className="text-xs leading-5 text-blue-800">Chỉ sử dụng tài khoản kỹ thuật viên đã được cửa hàng kích hoạt.</p></div>{error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{error}</p>}<label className="block text-sm font-semibold text-slate-700">Số điện thoại<div className="relative mt-2"><Phone className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400" /><input type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={e => setPhone(e.target.value)} required placeholder="0981 112 222" className="h-12 w-full rounded-xl border border-slate-200 pl-10 pr-4 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" /></div></label><label className="mt-5 block text-sm font-semibold text-slate-700">Mã PIN 6 số<div className="relative mt-2"><LockKeyhole className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400" /><input type={showPin ? 'text' : 'password'} inputMode="numeric" maxLength={6} value={pin} onChange={e => setPin(e.target.value.replace(/\D/g, ''))} required className="h-12 w-full rounded-xl border border-slate-200 px-10 text-lg tracking-[.35em] outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" /><button type="button" onClick={() => setShowPin(x => !x)} aria-label="Hiện hoặc ẩn PIN" className="absolute right-3 top-3 flex h-6 w-6 items-center justify-center text-slate-400">{showPin ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></label><button disabled={loading} className="mt-7 flex h-12 w-full items-center justify-center rounded-xl bg-blue-600 font-bold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 disabled:opacity-60">{loading ? 'Đang đăng nhập...' : 'Đăng nhập'}</button><p className="mt-5 text-center text-xs text-slate-400">Tài khoản demo: 0981112222 · PIN 123456</p></form></div></main>;
}
