import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, BriefcaseBusiness, CalendarDays, Camera, CheckCircle2, ChevronRight, Clock3, LogOut, MapPin, Navigation, Phone, RefreshCw, ShieldCheck, Star, UserRound, WalletCards, Wrench, XCircle } from 'lucide-react';
import technicianApi from '../services/technicianApi';
interface Job { id: string; customerName: string; customerPhone: string; customerAddress: string; district: string; applianceType: string; issueDescription: string; preferredDate: string; preferredTimeSlot: string; status: string; technicianDecision?: string; estimatedPrice?: number; inspectionNote?: string; customerApprovalStatus?: string; finalPrice?: number; note?: string; }
interface Tech { id: string; name: string; phone: string; avatar?: string; rating: number; completedCount: number; }
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + 'đ';
const statusLabel: Record<string, string> = { assigned: 'Chờ nhận việc', in_progress: 'Đang thực hiện', completed: 'Đã hoàn thành', cancelled: 'Đã hủy' };
export default function TechnicianPortal() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [tab, setTab] = useState<'jobs' | 'earnings'>('jobs'); const [selected, setSelected] = useState<Job | null>(null); const [toast, setToast] = useState('');
  const token = localStorage.getItem('dl247_technician_token'); const stored: Tech | null = (() => { try { return JSON.parse(localStorage.getItem('dl247_technician') || 'null'); } catch { return null; } })();
  useEffect(() => { if (!token) navigate('/technician/login', { replace: true }); }, [token, navigate]);
  const jobsQuery = useQuery({ queryKey: ['technician-jobs'], queryFn: async () => (await technicianApi.get('/technician/jobs')).data.data as Job[], enabled: !!token, refetchInterval: 20000 });
  const earningsQuery = useQuery({ queryKey: ['technician-earnings'], queryFn: async () => (await technicianApi.get('/technician/earnings')).data.data, enabled: !!token && tab === 'earnings' });
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3000); };
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['technician-jobs'] }); queryClient.invalidateQueries({ queryKey: ['technician-earnings'] }); };
  const action = useMutation({ mutationFn: async ({ path, data }: { path: string; data: unknown }) => technicianApi.patch(path, data), onSuccess: response => { refresh(); const job = response.data.data; setSelected(job?.id ? job : null); notify(response.data.message || 'Cập nhật thành công'); }, onError: (error: { response?: { data?: { message?: string } } }) => notify(error.response?.data?.message || 'Không thể cập nhật công việc') });
  const jobs = jobsQuery.data || []; const today = new Date().toISOString().slice(0, 10); const todayJobs = jobs.filter(job => job.preferredDate === today && !['completed', 'cancelled'].includes(job.status)); const upcoming = jobs.filter(job => job.preferredDate !== today && !['completed', 'cancelled'].includes(job.status));
  const logout = async () => { try { await technicianApi.post('/technician/auth/logout'); } catch { /* clear local session regardless */ } localStorage.removeItem('dl247_technician_token'); localStorage.removeItem('dl247_technician'); navigate('/technician/login', { replace: true }); };
  if (selected) return <JobDetail job={selected} busy={action.isPending} onBack={() => { setSelected(null); refresh(); }} onAction={(path, data) => action.mutate({ path, data })} />;
  return <main className="min-h-screen bg-slate-100 pb-24"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-4"><div className="flex items-center gap-3"><img src={stored?.avatar} alt="" className="h-10 w-10 rounded-xl bg-slate-100 object-cover" /><div><p className="text-xs text-slate-400">Xin chào,</p><h1 className="text-sm font-bold text-slate-900">{stored?.name || 'Kỹ thuật viên'}</h1></div></div><div className="flex gap-1"><button onClick={() => jobsQuery.refetch()} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100" aria-label="Làm mới"><RefreshCw className={`h-5 w-5 ${jobsQuery.isFetching ? 'animate-spin' : ''}`} /></button><button onClick={logout} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-red-50 hover:text-red-600" aria-label="Đăng xuất"><LogOut className="h-5 w-5" /></button></div></div></header><div className="mx-auto max-w-3xl px-4 py-6"><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 to-blue-950 p-6 text-white shadow-xl"><div className="flex items-start justify-between"><div><p className="text-sm text-cyan-300">Công việc hôm nay</p><strong className="mt-1 block text-4xl">{todayJobs.length}</strong><p className="mt-2 text-xs text-slate-400">{todayJobs.filter(job => job.status === 'in_progress').length} việc đang thực hiện</p></div><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10"><BriefcaseBusiness className="h-6 w-6 text-cyan-300" /></span></div><div className="mt-5 flex items-center gap-2 border-t border-white/10 pt-4 text-xs text-slate-300"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />{stored?.rating || 5}/5 · {stored?.completedCount || 0} công việc đã hoàn thành</div></section>
    {tab === 'jobs' ? <div className="mt-7 space-y-7"><JobSection title="Lịch hôm nay" subtitle="Ưu tiên xử lý theo thứ tự thời gian" jobs={todayJobs} onSelect={setSelected} empty="Không có công việc nào hôm nay." /><JobSection title="Lịch sắp tới" subtitle="Các công việc đã được phân công" jobs={upcoming} onSelect={setSelected} empty="Chưa có lịch sắp tới." /></div> : <Earnings data={earningsQuery.data} loading={earningsQuery.isLoading} />}</div><nav className="fixed inset-x-0 bottom-0 z-30 border-t border-slate-200 bg-white/95 px-4 pb-[max(.7rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur"><div className="mx-auto grid max-w-sm grid-cols-2 gap-2"><button onClick={() => setTab('jobs')} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl text-sm font-bold ${tab === 'jobs' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-500'}`}><CalendarDays className="h-5 w-5" />Công việc</button><button onClick={() => setTab('earnings')} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl text-sm font-bold ${tab === 'earnings' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-500'}`}><WalletCards className="h-5 w-5" />Thu nhập</button></div></nav>{toast && <div className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white shadow-xl">{toast}</div>}</main>;
}
function JobSection({ title, subtitle, jobs, onSelect, empty }: { title: string; subtitle: string; jobs: Job[]; onSelect: (job: Job) => void; empty: string }) { return <section><div className="mb-3"><h2 className="font-bold text-slate-950">{title}</h2><p className="mt-0.5 text-xs text-slate-500">{subtitle}</p></div><div className="space-y-3">{jobs.length ? jobs.map(job => <button key={job.id} onClick={() => onSelect(job)} className="group w-full rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><div className="flex justify-between gap-3"><div><span className="text-xs font-bold text-blue-600">{job.id}</span><h3 className="mt-1 font-bold text-slate-900">{job.applianceType} · {job.issueDescription}</h3></div><ChevronRight className="h-5 w-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-500" /></div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-slate-100 pt-3 text-xs text-slate-500"><span className="flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />{job.preferredTimeSlot}</span><span className="flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5" />{job.district}</span></div><span className={`mt-3 inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${job.status === 'in_progress' ? 'bg-cyan-50 text-cyan-700' : 'bg-amber-50 text-amber-700'}`}>{statusLabel[job.status] || job.status}</span></button>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-400">{empty}</div>}</div></section>; }
function JobDetail({ job, busy, onBack, onAction }: { job: Job; busy: boolean; onBack: () => void; onAction: (path: string, data: unknown) => void }) { const [mode, setMode] = useState<'none' | 'reject' | 'inspection' | 'complete'>('none'); const [photos, setPhotos] = useState<string[]>([]); const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${job.customerAddress}, ${job.district}`)}`; const readPhotos = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []).slice(0, 4); const data = await Promise.all(files.map(file => new Promise<string>(resolve => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }))); setPhotos(data); };
  return <main className="min-h-screen bg-slate-100 pb-8"><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur"><button onClick={onBack} className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-xs text-slate-400">Chi tiết công việc</p><h1 className="font-bold text-slate-950">{job.id}</h1></div></header><div className="mx-auto max-w-2xl space-y-4 p-4"><section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex justify-between gap-4"><div><span className="text-xs font-bold text-cyan-300">{statusLabel[job.status] || job.status}</span><h2 className="mt-2 text-xl font-bold">{job.applianceType}</h2><p className="mt-1 text-sm text-slate-300">{job.issueDescription}</p></div><Wrench className="h-7 w-7 text-cyan-300" /></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-white/10 pt-4 text-xs text-slate-300"><span><Clock3 className="mr-1.5 inline h-4 w-4" />{job.preferredTimeSlot}</span><span><CalendarDays className="mr-1.5 inline h-4 w-4" />{new Date(`${job.preferredDate}T00:00:00`).toLocaleDateString('vi-VN')}</span></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><UserRound className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-900">{job.customerName}</h2><p className="mt-0.5 text-sm text-slate-500">{job.customerAddress}, {job.district}</p></div></div><div className="mt-4 grid grid-cols-2 gap-3"><a href={`tel:${job.customerPhone}`} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-emerald-600 text-sm font-bold text-white"><Phone className="h-5 w-5" />Gọi khách</a><a href={mapUrl} target="_blank" rel="noreferrer" className="flex h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-bold text-white"><Navigation className="h-5 w-5" />Mở bản đồ</a></div></section>
    {!job.technicianDecision && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-900">Phản hồi công việc</h2><p className="mt-1 text-sm text-slate-500">Xác nhận sớm để điều phối viên biết bạn đã nhận lịch.</p><div className="mt-4 grid grid-cols-2 gap-3"><button disabled={busy} onClick={() => onAction(`/technician/jobs/${job.id}/decision`, { decision: 'accepted' })} className="h-12 rounded-xl bg-blue-600 text-sm font-bold text-white"><CheckCircle2 className="mr-2 inline h-5 w-5" />Nhận việc</button><button disabled={busy} onClick={() => setMode('reject')} className="h-12 rounded-xl border border-red-200 text-sm font-bold text-red-600"><XCircle className="mr-2 inline h-5 w-5" />Từ chối</button></div></section>}
    {job.technicianDecision === 'accepted' && job.status === 'assigned' && <button disabled={busy} onClick={() => onAction(`/technician/jobs/${job.id}/progress`, { status: 'in_progress' })} className="flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-orange-500 font-bold text-white shadow-lg shadow-orange-500/20"><Wrench className="h-5 w-5" />Bắt đầu kiểm tra</button>}
    {job.status === 'in_progress' && <section className="grid grid-cols-2 gap-3"><button onClick={() => setMode('inspection')} className="min-h-24 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-left text-blue-800"><ShieldCheck className="h-5 w-5" /><strong className="mt-3 block text-sm">Chẩn đoán & chi phí</strong></button><button disabled={job.customerApprovalStatus !== 'approved'} onClick={() => setMode('complete')} className="min-h-24 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-left text-emerald-800 disabled:opacity-40"><CheckCircle2 className="h-5 w-5" /><strong className="mt-3 block text-sm">Hoàn thành công việc</strong></button></section>}
    {mode === 'reject' && <ActionForm title="Lý do từ chối" onClose={() => setMode('none')} onSubmit={form => onAction(`/technician/jobs/${job.id}/decision`, { decision: 'rejected', reason: form.get('reason') })}><textarea name="reason" required minLength={3} rows={4} className="portal-input h-auto py-3" placeholder="Nêu rõ lý do để điều phối viên sắp xếp thợ khác..." /></ActionForm>}
    {mode === 'inspection' && <ActionForm title="Chẩn đoán và chi phí" onClose={() => setMode('none')} onSubmit={form => onAction(`/technician/jobs/${job.id}/inspection`, { diagnosis: form.get('diagnosis'), estimatedPrice: Number(form.get('estimatedPrice')), customerApprovalStatus: form.get('approval') })}><textarea name="diagnosis" defaultValue={job.inspectionNote} required minLength={3} rows={4} className="portal-input h-auto py-3" placeholder="Nguyên nhân và hạng mục cần sửa..." /><input name="estimatedPrice" defaultValue={job.estimatedPrice || ''} type="number" min="1" required className="portal-input" placeholder="Chi phí dự kiến (VNĐ)" /><select name="approval" defaultValue={job.customerApprovalStatus || 'pending'} className="portal-input"><option value="pending">Đã báo — chờ khách đồng ý</option><option value="approved">Khách đã đồng ý</option><option value="rejected">Khách từ chối</option></select></ActionForm>}
    {mode === 'complete' && <ActionForm title="Hoàn thành công việc" onClose={() => setMode('none')} onSubmit={form => onAction(`/technician/jobs/${job.id}/complete`, { completionNote: form.get('note'), finalPrice: Number(form.get('finalPrice')), paymentStatus: form.get('paymentStatus'), photos })}><textarea name="note" required minLength={3} rows={3} className="portal-input h-auto py-3" placeholder="Nội dung đã thực hiện..." /><input name="finalPrice" type="number" min="1" defaultValue={job.estimatedPrice} required className="portal-input" placeholder="Chi phí cuối cùng" /><select name="paymentStatus" className="portal-input"><option value="unpaid">Chưa thanh toán</option><option value="paid">Đã thanh toán</option></select><label className="flex min-h-24 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-200 text-sm font-semibold text-slate-500"><Camera className="mb-2 h-5 w-5 text-blue-600" />Chụp ảnh sau sửa<input type="file" accept="image/*" capture="environment" multiple onChange={readPhotos} className="sr-only" /></label>{photos.length > 0 && <p className="text-xs font-medium text-emerald-600">Đã chọn {photos.length} ảnh</p>}</ActionForm>}
  </div></main>; }
function ActionForm({ title, children, onClose, onSubmit }: { title: string; children: React.ReactNode; onClose: () => void; onSubmit: (data: FormData) => void }) { return <form onSubmit={e => { e.preventDefault(); onSubmit(new FormData(e.currentTarget)); }} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-lg"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-slate-950">{title}</h2><button type="button" onClick={onClose} className="text-sm font-semibold text-slate-400">Đóng</button></div><div className="space-y-3">{children}</div><button className="mt-4 h-12 w-full rounded-xl bg-blue-600 font-bold text-white">Lưu cập nhật</button></form>; }
function Earnings({ data, loading }: { data?: { total: number; thisMonth: number; jobs: { id: string; completedAt: string; revenue: number; earning: number }[] }; loading: boolean }) { if (loading) return <div className="mt-8 text-center text-sm text-slate-400">Đang tính thu nhập...</div>; return <div className="mt-7 space-y-5"><section className="rounded-3xl bg-gradient-to-br from-emerald-600 to-teal-700 p-6 text-white shadow-xl"><WalletCards className="h-7 w-7 text-emerald-100" /><p className="mt-5 text-sm text-emerald-100">Thu nhập tháng này</p><strong className="mt-1 block text-3xl">{money(data?.thisMonth || 0)}</strong><p className="mt-3 text-xs text-emerald-100">Tổng lũy kế: {money(data?.total || 0)}</p></section><section><h2 className="font-bold text-slate-950">Đối soát công việc</h2><div className="mt-3 space-y-2">{data?.jobs?.length ? data.jobs.map(item => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4"><div><p className="text-sm font-bold text-slate-900">{item.id}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.completedAt).toLocaleDateString('vi-VN')} · Doanh thu {money(item.revenue)}</p></div><strong className="text-sm text-emerald-600">+{money(item.earning)}</strong></div>) : <p className="rounded-2xl bg-white p-8 text-center text-sm text-slate-400">Chưa có công việc đã đối soát.</p>}</div></section></div>; }
