import { useState } from 'react';
import { CalendarDays, CheckCircle2, Phone, Search, ShieldCheck, UserRound, Wrench } from 'lucide-react';
import api from '../services/api';
import Input from '../components/ui/Input';
import Button from '../components/ui/Button';
import type { GuestLookupServiceRequest } from '../types/service';
import useDocumentTitle from '../hooks/useDocumentTitle';
import { useSettings } from '../hooks/useSettings';

const statusLabels: Record<string, string> = { pending: 'Mới tiếp nhận', confirmed: 'Đã xác nhận', assigned: 'Đã phân công thợ', in_progress: 'Đang sửa chữa', completed: 'Đã hoàn thành', cancelled: 'Đã hủy' };
const statusOrder = ['pending', 'confirmed', 'assigned', 'in_progress', 'completed'];
export default function TrackService() {
  useDocumentTitle('Tra cứu yêu cầu sửa chữa'); const { settings } = useSettings();
  const last = (() => { try { return JSON.parse(localStorage.getItem('dl247-last-booking') || 'null'); } catch { return null; } })();
  const [requestCode, setRequestCode] = useState(last?.requestId || ''); const [phone, setPhone] = useState(last?.phone || ''); const [otp, setOtp] = useState('');
  const [step, setStep] = useState<'identify'|'verify'|'done'>('identify'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [request, setRequest] = useState<GuestLookupServiceRequest | null>(null); const [lookupToken,setLookupToken]=useState('');
  const requestOtp = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api.post('/service-requests/lookup/request-otp', { requestCode: requestCode.trim().toUpperCase(), phone: phone.replace(/[\s.-]/g, '') }); setStep('verify'); } catch { setError('Không thể gửi mã xác thực lúc này. Vui lòng thử lại sau.'); } finally { setBusy(false); } };
  const verify = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const verified = await api.post('/service-requests/lookup/verify', { requestCode: requestCode.trim().toUpperCase(), otp }); const token = verified.data.data.token; const detail = await api.get(`/service-requests/lookup/${encodeURIComponent(requestCode.trim().toUpperCase())}`, { headers: { Authorization: `Lookup ${token}` } }); setLookupToken(token); setRequest(detail.data.data); setStep('done'); } catch { setError('Mã xác thực không hợp lệ hoặc đã hết hạn.'); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Search className="h-6 w-6" /></span><h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-950">Theo dõi yêu cầu sửa chữa</h1><p className="mt-3 text-sm leading-6 text-slate-500">Xác thực một lần bằng OTP để xem đúng yêu cầu này. Mã truy cập ngắn hạn không mở toàn bộ lịch sử.</p></div>
    {step === 'identify' && <form onSubmit={requestOtp} className="mx-auto mt-8 grid max-w-2xl gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-lg sm:grid-cols-[1fr_1fr_auto] sm:items-end sm:p-6"><Input label="Mã yêu cầu" value={requestCode} onChange={e=>setRequestCode(e.target.value.toUpperCase())} required /><Input label="Số điện thoại đặt lịch" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} required /><Button type="submit" isLoading={busy}>Gửi OTP</Button></form>}
    {step === 'verify' && <form onSubmit={verify} className="mx-auto mt-8 max-w-md space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-lg"><Input label="Mã OTP 6 số" inputMode="numeric" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} required /><Button type="submit" isLoading={busy} className="w-full">Xác thực và xem tiến độ</Button><button type="button" onClick={()=>{setStep('identify');setOtp('');setError('');}} className="w-full text-sm text-slate-500">Nhập lại thông tin</button></form>}
    {error && <div role="alert" className="mx-auto mt-5 max-w-2xl rounded-2xl border border-red-200 bg-red-50 p-4 text-center text-sm font-medium text-red-800">{error}</div>}
    {step === 'done' && request && <div className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="flex justify-between bg-slate-950 p-6 text-white"><div><p className="text-xs text-cyan-300">Mã yêu cầu</p><h2 className="text-2xl font-bold">{request.id}</h2></div><span>{statusLabels[request.status] || request.status}</span></div><div className="p-6"><StatusTimeline status={request.status}/><div className="mt-8 grid gap-4 sm:grid-cols-2"><InfoCard icon={Wrench} label="Thiết bị" value={request.applianceType} detail={request.issueDescription}/><InfoCard icon={CalendarDays} label="Lịch hẹn" value={`${request.preferredTimeSlot} · ${request.preferredDate}`} detail={request.district}/><InfoCard icon={UserRound} label="Kỹ thuật viên" value={request.technician?.name || 'Đang chờ phân công'} detail="Thông tin liên hệ được bảo vệ"/><InfoCard icon={ShieldCheck} label="Chi phí" value={request.finalPrice ? `${request.finalPrice.toLocaleString('vi-VN')}đ` : 'Chưa có chi phí chính thức'} detail="Được xác nhận trước khi sửa"/></div>{request.quote?.status === 'sent' && <div className="mt-5 flex gap-3"><Button onClick={async()=>{await api.post(`/service-quotes/${request.quote!.id}/guest-decision`,{decision:'approved'},{headers:{Authorization:`Lookup ${lookupToken}`}});setRequest({...request,quote:{...request.quote!,status:'approved'}});}}>Đồng ý báo giá</Button><Button variant="outline" onClick={async()=>{await api.post(`/service-quotes/${request.quote!.id}/guest-decision`,{decision:'rejected'},{headers:{Authorization:`Lookup ${lookupToken}`}});setRequest({...request,quote:{...request.quote!,status:'rejected'}});}}>Từ chối</Button></div>}<a href={`tel:${settings.hotline.replace(/\s+/g,'')}`} className="mt-6 flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 text-white"><Phone className="h-4 w-4"/>Gọi {settings.hotline}</a></div></div>}
  </div>;
}
function StatusTimeline({status}:{status:string}) { if(status==='cancelled') return <div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">Yêu cầu đã được hủy.</div>; const current=statusOrder.indexOf(status); return <div className="grid grid-cols-5">{statusOrder.map((item,index)=><div key={item} className="text-center"><span className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full ${index<=current?'bg-blue-600 text-white':'bg-slate-200'}`}>{index<current?<CheckCircle2 className="h-4 w-4"/>:index+1}</span><span className="mt-2 hidden text-xs sm:block">{statusLabels[item]}</span></div>)}</div>; }
function InfoCard({icon:Icon,label,value,detail}:{icon:typeof Wrench;label:string;value:string;detail:string}) { return <div className="flex gap-3 rounded-2xl border p-4"><Icon className="h-5 w-5 text-blue-600"/><div><p className="text-xs text-slate-400">{label}</p><p className="font-bold">{value}</p><p className="text-sm text-slate-500">{detail}</p></div></div>; }
