import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CalendarDays, CheckCircle2, Phone, Search, ShieldCheck, UserRound, Wrench } from 'lucide-react';
import api from '../services/api';
import Input from '../components/ui/Input';
import Button from '../components/ui/Button';
import type { ServiceRequest } from '../types/service';
import useDocumentTitle from '../hooks/useDocumentTitle';
import { useSettings } from '../hooks/useSettings';

const statusLabels: Record<string, string> = { pending: 'Mới tiếp nhận', confirmed: 'Đã xác nhận', assigned: 'Đã phân công thợ', in_progress: 'Đang sửa chữa', completed: 'Đã hoàn thành', cancelled: 'Đã hủy' };
const statusOrder = ['pending', 'confirmed', 'assigned', 'in_progress', 'completed'];

export default function TrackService() {
  useDocumentTitle('Tra cứu yêu cầu sửa chữa');
  const { settings } = useSettings();
  const last = (() => { try { return JSON.parse(localStorage.getItem('dl247-last-booking') || 'null'); } catch { return null; } })();
  const [requestCode, setRequestCode] = useState(last?.requestId || '');
  const [phone, setPhone] = useState(last?.phone || '');
  const [lookup, setLookup] = useState<{ code: string; phone: string } | null>(null);
  const query = useQuery({ queryKey: ['public-service-lookup', lookup?.code, lookup?.phone], queryFn: async () => (await api.get(`/service-requests/lookup/${encodeURIComponent(lookup!.code)}`, { params: { phone: lookup!.phone } })).data, enabled: Boolean(lookup), retry: false });
  const request: ServiceRequest | undefined = query.data?.data;
  const submit = (event: React.FormEvent) => { event.preventDefault(); const cleanPhone = phone.replace(/[\s.-]/g, ''); if (!requestCode.trim() || !cleanPhone) return; setLookup({ code: requestCode.trim().toUpperCase(), phone: cleanPhone }); };

  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Search className="h-6 w-6" /></span><h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-950">Theo dõi yêu cầu sửa chữa</h1><p className="mt-3 text-sm leading-6 text-slate-500">Nhập mã yêu cầu và số điện thoại đã dùng khi đặt lịch. Bạn không cần đăng nhập.</p></div>
    <form onSubmit={submit} className="mx-auto mt-8 grid max-w-2xl gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-lg shadow-slate-900/5 sm:grid-cols-[1fr_1fr_auto] sm:items-end sm:p-6"><Input label="Mã yêu cầu" value={requestCode} onChange={e => setRequestCode(e.target.value.toUpperCase())} placeholder="Ví dụ: SR-123456" /><Input label="Số điện thoại" type="tel" inputMode="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="0912 345 678" /><Button type="submit" isLoading={query.isFetching} leftIcon={<Search className="h-4 w-4" />} className="h-11 font-bold">Tra cứu</Button></form>
    {query.error && <div role="alert" className="mx-auto mt-5 max-w-2xl rounded-2xl border border-red-200 bg-red-50 p-4 text-center text-sm font-medium text-red-800">Không tìm thấy yêu cầu phù hợp. Vui lòng kiểm tra lại mã và số điện thoại.</div>}
    {request && <div className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-900/5"><div className="flex flex-col gap-4 bg-slate-950 p-6 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-cyan-300">Mã yêu cầu</p><h2 className="mt-1 text-2xl font-bold">{request.id}</h2><p className="mt-1 text-sm text-slate-400">Gửi lúc {new Date(request.createdAt).toLocaleString('vi-VN')}</p></div><span className="w-fit rounded-full bg-blue-500/20 px-4 py-2 text-sm font-bold text-blue-200">{statusLabels[request.status] || request.status}</span></div>
      <div className="p-5 sm:p-7"><StatusTimeline status={request.status} /><div className="mt-8 grid gap-4 sm:grid-cols-2"><InfoCard icon={Wrench} label="Thiết bị & tình trạng" value={request.applianceType} detail={request.issueDescription} /><InfoCard icon={CalendarDays} label="Lịch hẹn" value={`${request.preferredTimeSlot} · ${new Date(`${request.preferredDate}T00:00:00`).toLocaleDateString('vi-VN')}`} detail={`${request.customerAddress}, ${request.district}`} /><InfoCard icon={UserRound} label="Kỹ thuật viên" value={request.technician?.name || 'Đang chờ phân công'} detail={request.technician ? `Đánh giá ${request.technician.rating.toFixed(1)}/5` : 'Chúng tôi sẽ cập nhật sau khi xác nhận lịch.'} /><InfoCard icon={ShieldCheck} label="Chi phí" value={request.finalPrice ? new Intl.NumberFormat('vi-VN').format(request.finalPrice) + 'đ' : 'Chưa có chi phí chính thức'} detail="Kỹ thuật viên sẽ thông báo để bạn đồng ý trước khi sửa." /></div>
        <div className="mt-6 flex flex-col items-center justify-between gap-4 rounded-2xl bg-blue-50 p-4 sm:flex-row"><div className="flex items-center gap-3"><Phone className="h-5 w-5 text-blue-600" /><div><p className="text-sm font-bold text-blue-950">Bạn cần hỗ trợ?</p><p className="text-xs text-blue-700">Cung cấp mã {request.id} khi liên hệ.</p></div></div><a href={`tel:${settings.hotline.replace(/\s+/g, '')}`} className="inline-flex min-h-11 items-center rounded-xl bg-blue-600 px-5 text-sm font-bold text-white">Gọi {settings.hotline}</a></div></div></div>}
  </div>;
}
function StatusTimeline({ status }: { status: string }) { if (status === 'cancelled') return <div className="rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-800">Yêu cầu này đã được hủy. Vui lòng liên hệ hotline nếu bạn cần hỗ trợ thêm.</div>; const current = statusOrder.indexOf(status); return <div><h3 className="text-sm font-bold text-slate-900">Tiến độ xử lý</h3><div className="mt-5 grid grid-cols-5">{statusOrder.map((item, index) => <div key={item} className="relative flex flex-col items-center text-center"><div className={`absolute left-0 right-0 top-4 h-0.5 ${index <= current ? 'bg-blue-600' : 'bg-slate-200'} ${index === 0 ? 'left-1/2' : ''} ${index === statusOrder.length - 1 ? 'right-1/2' : ''}`} /><span className={`relative z-10 flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${index <= current ? 'bg-blue-600 text-white' : 'bg-slate-200 text-slate-500'}`}>{index < current ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</span><span className={`mt-2 hidden text-[11px] font-semibold sm:block ${index <= current ? 'text-blue-700' : 'text-slate-400'}`}>{statusLabels[item]}</span></div>)}</div></div>; }
function InfoCard({ icon: Icon, label, value, detail }: { icon: typeof Wrench; label: string; value: string; detail: string }) { return <div className="flex gap-3 rounded-2xl border border-slate-200 p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><Icon className="h-5 w-5" /></span><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p><p className="mt-1 text-sm leading-5 text-slate-500">{detail}</p></div></div>; }
